version: "3"

services:

    server:
        container_name: server
        build: .
        ports:
            - "8080:8080"
        networks:
            - webnet

    prometheus:
        container_name: prometheus
        depends_on:
          - server
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - webnet
        image: prom/prometheus:v2.40.7

    grafana:
        container_name: grafana
        depends_on:
          - server
          - prometheus
        volumes:
            - ./grafana/config.ini:/etc/grafana/grafana.ini
            - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yaml
            - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml
            - ./grafana/dashboards:/var/lib/grafana/dashboards
        ports:
            - "3000:3000"
        networks:
            - webnet
        image: grafana/grafana:9.4.2


networks:
  webnet:
    driver: bridge